"""Profile data for person-name themes.

Maps canonical short name -> full name + info for disambiguation.
"""

PROFILES: dict[str, dict[str, dict[str, str]]] = {
    "ai": {
        "altman": {"full_name": "Sam Altman", "info": "CEO of OpenAI"},
        "dario": {"full_name": "Dario Amodei", "info": "CEO of Anthropic"},
        "ilya": {
            "full_name": "Ilya Sutskever",
            "zh": "伊利亚",
            "info": "Co-founder of SSI, former OpenAI chief scientist",
        },
        "lecun": {"full_name": "Yann LeCun", "info": "Chief AI Scientist at Meta, Turing Award winner"},
        "karpathy": {"full_name": "Andrej Karpathy", "info": "Founder of Eureka Labs, former Tesla AI director"},
        "hassabis": {"full_name": "Demis Hassabis", "info": "CEO of Google DeepMind, Nobel laureate"},
        "vaswani": {
            "full_name": "Ashish Vaswani",
            "info": "Lead author of Attention Is All You Need, Transformer inventor",
        },
        "hinton": {"full_name": "Geoffrey Hinton", "info": "Godfather of deep learning, Turing & Nobel laureate"},
        "bengio": {"full_name": "Yoshua Bengio", "info": "Mila founder, Turing Award winner"},
        "fei-fei": {"full_name": "Fei-Fei Li", "zh": "李飞飞", "info": "Stanford HAI co-director, ImageNet creator"},
        "ng": {"full_name": "Andrew Ng", "zh": "吴恩达", "info": "DeepLearning.AI founder, former Baidu VP"},
        "zuck": {"full_name": "Mark Zuckerberg", "info": "CEO of Meta"},
        "bezos": {"full_name": "Jeff Bezos", "info": "Founder of Amazon & Blue Origin"},
        "nadella": {"full_name": "Satya Nadella", "info": "CEO of Microsoft"},
        "pichai": {"full_name": "Sundar Pichai", "info": "CEO of Google & Alphabet"},
        "musk": {"full_name": "Elon Musk", "info": "CEO of Tesla, SpaceX, xAI"},
        "huang": {"full_name": "Jensen Huang", "zh": "黄仁勋", "info": "CEO of NVIDIA"},
        "lisa-su": {"full_name": "Lisa Su", "zh": "苏姿丰", "info": "CEO of AMD"},
        "radford": {"full_name": "Alec Radford", "info": "GPT & CLIP author, OpenAI researcher"},
        "jack-clark": {"full_name": "Jack Clark", "info": "Co-founder of Anthropic"},
    },
    "threebody": {
        "luo-ji": {"full_name": "罗辑 (Luo Ji)", "info": "面壁者、执剑人，黑暗森林威慑的守护者"},
        "shi-qiang": {"full_name": "史强 (Shi Qiang)", "info": "刑警，人称大史，罗辑的搭档与守护者"},
        "ye-wenjie": {"full_name": "叶文洁 (Ye Wenjie)", "info": "天体物理学家，红岸工程负责人，三体危机的起源"},
        "cheng-xin": {"full_name": "程心 (Cheng Xin)", "info": "航天工程师，第二任执剑人，阶梯计划发起者"},
        "zhang-beihai": {
            "full_name": "章北海 (Zhang Beihai)",
            "info": "海军政委，面壁者式的钢印战士，自然选择号劫持者",
        },
        "yun-tianming": {
            "full_name": "云天明 (Yun Tianming)",
            "info": "通过阶梯计划将大脑送往三体舰队，用三个童话传递情报",
        },
        "wang-miao": {"full_name": "汪淼 (Wang Miao)", "info": "纳米材料学家，三体游戏玩家，古筝行动参与者"},
        "ding-yi": {"full_name": "丁仪 (Ding Yi)", "info": "理论物理学家，研究球状闪电和宏原子"},
        "yang-dong": {"full_name": "杨冬 (Yang Dong)", "info": "粒子物理学家，叶文洁之女，因物理学不存在而绝望"},
        "zhuang-yan": {"full_name": "庄颜 (Zhuang Yan)", "info": "罗辑的妻子，梦中人变为现实"},
        "guan-yifan": {"full_name": "关一帆 (Guan Yifan)", "info": "引力波宇宙学家，与程心一同进入小宇宙"},
        "shen-yufei": {"full_name": "申玉菲 (Shen Yufei)", "info": "物理学家，三体组织成员，降临派"},
        "wei-cheng": {"full_name": "魏成 (Wei Cheng)", "info": "数学家，申玉菲之夫，研究三体问题数学解"},
        "hines": {"full_name": "Bill Hines (比尔·希恩斯)", "info": "面壁者，脑科学家，思想钢印发明者"},
        "tyler": {"full_name": "Frederick Tyler (弗雷德里克·泰勒)", "info": "面壁者，前美国国防部长"},
        "wade": {"full_name": "Thomas Wade (托马斯·维德)", "info": "PIA 局长，光速飞船的推动者，不择手段的战略家"},
        "evans": {"full_name": "Mike Evans (迈克·伊文斯)", "info": "地球三体组织统帅，审判日号船长"},
        "rey-diaz": {
            "full_name": "Manuel Rey Diaz (曼努尔·雷迪亚兹)",
            "info": "面壁者，前委内瑞拉总统，恒星型氢弹计划",
        },
        "tomoko": {"full_name": "智子 (Tomoko/Sophon)", "info": "三体人用质子展开制造的超级计算机，也是人形使者"},
        "singer": {"full_name": "歌者 (Singer)", "info": "歌者文明的清理员，向太阳系发射二向箔"},
    },
    "titan": {
        "wang-xingxing": {"full_name": "王兴兴 (Wang Xingxing)", "info": "宇树科技创始人，人形机器人先驱"},
        "ren-zhengfei": {"full_name": "任正非 (Ren Zhengfei)", "info": "华为创始人"},
        "zhang-yiming": {"full_name": "张一鸣 (Zhang Yiming)", "info": "字节跳动创始人"},
        "lei-jun": {"full_name": "雷军 (Lei Jun)", "info": "小米创始人"},
        "li-yanhong": {"full_name": "李彦宏 (Li Yanhong)", "info": "百度创始人兼CEO"},
        "li-kaifu": {"full_name": "李开复 (Kai-Fu Lee)", "info": "零一万物创始人，创新工场董事长"},
        "liang-wenfeng": {"full_name": "梁文锋 (Liang Wenfeng)", "info": "DeepSeek / 幻方量化创始人"},
        "yang-zhilin": {"full_name": "杨植麟 (Yang Zhilin)", "info": "月之暗面 (Moonshot AI / Kimi) 创始人"},
        "kaiming-he": {"full_name": "何恺明 (Kaiming He)", "info": "ResNet 作者，MIT 教授，前 FAIR 研究员"},
        "ma-huateng": {"full_name": "马化腾 (Ma Huateng)", "info": "腾讯创始人兼CEO"},
        "wang-jian": {"full_name": "王坚 (Wang Jian)", "info": "阿里云创始人，中国工程院院士"},
        "lu-qi": {"full_name": "陆奇 (Lu Qi)", "info": "奇绩创坛创始人，前百度COO、微软副总裁"},
        "goodfellow": {"full_name": "Ian Goodfellow", "info": "GAN 发明者"},
        "schmidhuber": {"full_name": "Jürgen Schmidhuber", "info": "LSTM 共同发明者，IDSIA 科学主任"},
        "dean": {"full_name": "Jeff Dean", "info": "Google Chief Scientist，MapReduce/TensorFlow 作者"},
        "chollet": {"full_name": "François Chollet", "info": "Keras 作者，ARC 基准提出者"},
        "silver": {"full_name": "David Silver", "info": "AlphaGo 首席研究员，DeepMind"},
        "carmack": {"full_name": "John Carmack", "info": "Doom/Quake 之父，前 Oculus CTO"},
        "torvalds": {"full_name": "Linus Torvalds", "info": "Linux & Git 创始人"},
        "wolfram": {"full_name": "Stephen Wolfram", "info": "Mathematica 创始人，Wolfram Research CEO"},
    },
}
